### PR TITLE
Added English breakdowns for sequence comps and self-ref sequence comps

### PR DESCRIPTION
**Pull request by jpziegler**

### CODE REVIEW

**Comment by WeeknightMVP** [comment]
This English strikes me as sufficiently explanatory, but I'm not the target audience.  Self-referential comprehensions can be difficult to grok even with a clear explanation.  Have we drawn, or drawn from, pictures of such?  I'm sure there are some nice LFSR diagrams somewhere.

**Comment by jpziegler** [comment]
We good now?

**Comment by WeeknightMVP** [comment]
Sorry I neglected to add the bars back after escaping.

Some of the longer definitions like `sayHello`, `addMult`, and maybe `roundKeys` should be split into multiple lines -- basically any tables that line-split cells in the type definition.  Otherwise the table formatting defeats the purpose of breaking the information down to make type definitions readable in the first place.

**Comment by weaversa** [comment]
@AssemblyZig would you be willing to go through and polish up the tables like you did another PR?

**Comment by AssemblyZig** [comment]
Sure, but it may not be for a week or so.

Cheers,
Zig

**Comment by WeeknightMVP** [comment]
@weaversa It appears your concerns over misalignment were corrected by escaping the bars in question: `\|`.

**Pull request merged**
