### PR TITLE
Bittwiddling exercises

### PR DESCRIPTION
**Pull request by weaversa**

### CODE REVIEW

**Comment by weaversa** [comment]
These need a narrative for the distance learner to follow along with.

Also, we don't expect `abc` to be installed (it's certainly not installed in the docker instances from Galois), so let's make sure the proofs all work with z3.

**Comment by weaversa** [comment]
Let's also clean these defaulting warnings.

```
[cryptol-course]$ cryptol labs/bittwiddling/bittwiddling.cry 
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.8.1 (e914cef)
https://cryptol.net  :? for help

Loading module Cryptol
Loading module Main
[warning] at labs/bittwiddling/bittwiddling.cry:33:50--33:61:
  Defaulting 2nd type argument of 'Main::parity64bit' to [0]
[warning] at labs/bittwiddling/bittwiddling.cry:33:50--33:61:
  Defaulting 1st type argument of 'Main::parity64bit' to [0]
[warning] at labs/bittwiddling/bittwiddling.cry:33:28--33:39:
  Defaulting 2nd type argument of 'Main::parity64bit' to [1]
[warning] at labs/bittwiddling/bittwiddling.cry:33:28--33:39:
  Defaulting 1st type argument of 'Main::parity64bit' to [1]
```

**Comment by weaversa** [comment]
@benjaminjellison Would you be willing to take a look at the [draft style-guide](https://github.com/weaversa/cryptol-course/blob/style-guide/cryptol-style.md) and try to clean up the .cry files? If not, I'm happy to do it.

**Comment by benjaminjellison** [comment]
Do you have a docker file for it?  I don't get those errors, but I'm running on Cryptol 2.7.

**Comment by weaversa** [comment]
@benjaminjellison Sure!

```
[cryptol-course]$ docker run -v $(pwd):/mnt/cryptol-course --env CRYPTOLPATH=/mnt/cryptol-course -it galoisinc/cryptol:2.8.0 
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.8.0

Loading module Cryptol
Cryptol> :l /mnt/cryptol-course/labs/bittwiddling/bittwiddling.cry
Loading module Cryptol
Loading module Main
[warning] at /mnt/cryptol-course/labs/bittwiddling/bittwiddling.cry:33:50--33:61:
  Defaulting 2nd type argument of 'Main::parity64bit' to [0]
[warning] at /mnt/cryptol-course/labs/bittwiddling/bittwiddling.cry:33:50--33:61:
  Defaulting 1st type argument of 'Main::parity64bit' to [0]
[warning] at /mnt/cryptol-course/labs/bittwiddling/bittwiddling.cry:33:28--33:39:
  Defaulting 2nd type argument of 'Main::parity64bit' to [1]
[warning] at /mnt/cryptol-course/labs/bittwiddling/bittwiddling.cry:33:28--33:39:
  Defaulting 1st type argument of 'Main::parity64bit' to [1]
```

**Comment by benjaminjellison** [comment]
Pushed a cleaned up version.  The warnings were useful, as the `bittwiddling.cry` didn't match `bittwiddling_answers.cry` in some places.  As for the format style, what do you think of the way I handle multiple conjunctions?

**Comment by weaversa** [comment]
I'd do this, I think:

```
testparity8bit : Bit
property testparity8bit = parity8bit 0x01 == True
                       /\ parity8bit 0x00 == False
                       /\ parity8bit 0xff == False
                       /\ parity8bit 0xef == True
```

Everything lines up. I changed everything to hex.

**Comment by weaversa** [comment]
Though, I think this is more in line with the style guide ---

```
testparity8bit : Bit
property testparity8bit =
    parity8bit 0x01 == True  /\
    parity8bit 0x00 == False /\
    parity8bit 0xff == False /\
    parity8bit 0xef == True
```

Yeah...that's even better...

**Comment by weaversa** [comment]
Consider making the comments into doc-comments so they show up under `:h` in the interpreter.

```
/**                                                                            
 * Determine the parity of a byte.  True if parity is odd, false if            
 * even.                                                                       
 */
```

**Comment by weaversa** [comment]
Actually, this really should be in markdown. For an example, see: https://github.com/weaversa/cryptol-course/blob/salsa20/labs/Salsa20/Salsa20.md

That file loads right into the interpreter.

**Comment by weaversa** [comment]
Would you be explicit about which parity you're referring to? https://mathworld.wolfram.com/Parity.html

When this is in markdown, you can even add a link to a nice definition, or provide your own definition using the markdown math mode.

**Comment by benjaminjellison** [comment]
Can SAW ingest markdown files?  I making a `cryptol_answers.md` ala the Salsa20 example, but when I try to run it in SAW it can't extract the functions.

**Comment by weaversa** [comment]
oh...I don' t know about `saw`...I bet there is a way. I'll try later.

**Comment by benjaminjellison** [comment]
It would be nicer to have it in `md` format, but I couldn't see how to get it to work with `saw`, which is the overall point of the exercises.  I didn't try that hard, so there may be a way.

**Comment by weaversa** [comment]
At the very least SAW deserves a bug report

**Comment by benjaminjellison** [comment]
I ran a test markdown file with the latest docker version of SAW (0.5) and it appeared to work.  I'll rewrite the bit twiddling exercises as a markdown.

**Comment by benjaminjellison** [comment]
I made `bittwiddling.md`, `bittwiddling_answers.md`, and `bittwiddling_answers.saw`.  Removed the extraneous `cry` files.

**Comment by weaversa** [comment]
Markdown works for me in `saw` with the latest version.

**Comment by weaversa** [comment]
This is a great intro SAW lab. I've moved it to `labs/saw` for now.

**Pull request merged**
