### PR TITLE
Flow tweaks

### PR DESCRIPTION
**Pull request by jdwoolc**
I think we talked about putting this up front, this pull request may be a good place to discuss the outline and README.md document in general.

### CODE REVIEW

**Comment by jdwoolc** [comment]
Agreed, I started to when I made my edit, but wasn't brave enough. I think
I know how it should go, just do it, and probably we'll adjust it a couple
times.

**Comment by weaversa** [comment]
Course outline has been reworked!

**Comment by weaversa** [comment]
@jdwoolc I love the idea of including the graph. Have you tried `rankdir="LR";`? I wonder if horizontal would look better...just a thing to try.

**Comment by jdwoolc** [comment]
I just threw together the simplest thing -- since you like it I'll keep playing around with the format a bit and spruce it up. Although, I think I'm still having trouble with the image link...

**Comment by jdwoolc** [comment]
I like the horizontal format with the vertical orientation for the preliminary material. I'm not sure the links are working in the README document though. Is there a different way to link to the SVG that picks up the embedded link information?

**Comment by weaversa** [comment]
> I like the horizontal format with the vertical orientation for the preliminary material. I'm not sure the links are working in the README document though. Is there a different way to link to the SVG that picks up the embedded link information?

The links work if you click the image first to get to here:
https://raw.githubusercontent.com/weaversa/cryptol-course/flow-tweaks/misc/deps.svg

I'm not sure how to get them to _just work_. I've googled around with no luck.

**Pull request merged**
