### PR TITLE
Lab simon speck

### PR DESCRIPTION
**Pull request by jdwoolc**
Here is a (fairly) rough draft of the Simon/Speck Parameterized Modules lab. I think it would benefit from some early eyeballs and comments on how to improve the exposition.

### CODE REVIEW

**Comment by WeeknightMVP** [comment]
Looks good so far.  I'll comment per relevant section below:

# Prerequisites

Maybe change "methods" to "functions" or change the whole bullet to something like "Know how to use basic type parameters in function definitions."

# Introducing Parameterized Modules

Could increase the variety in the opening "template", e.g.:
 * type parameters of arbitary type kind (`*`)
 * type constraints
 * value parameters
   + of built-in type
   + of user-defined type

```Cryptol
parameter
    /** numeric type parameter; must be a finite whole number */
    type param_NumType : #
    type constraint (fin param_NumType, param_NumType >= 1)

    /** arbitrary type parameter; must be comparable and logical */
    type param_AnyType : *
    type constraint (Cmp param_AnyType, Logic param_AnyType)

     /** unconstrained value parameter of built-in type */
    param_builtin: [16][8]

    /** value parameter of parameter type */
    param_val: param_AnyType

    /** unconstrained value parameter of type defined outside parameter scope */
    param_userdef : OtherType

/** a type defined outside parameter scope */
type OtherType = [param_NumType]param_AnyType

// ...other definitions in public scope; may use parameters defined above...
```

This would convey more parameterized module features, but at the risk of overwhelming a new user.

# Writing a Parameterized Module for Simon

We should decide whether grouping all parametric type constraints together vs. defining constraints per parameter or related set of parameters is a better practice.  I would lean toward the latter, as this clarifies the help documentation, e.g.

```Cryptol
parameter
  /** word size */
  type n : #
  type constraint (16 <= n, n <= 64)  // should infer `fin n`

  /** number of words in key */
  type m : #
  type constraint (2 <= m, m <= 4)  // should infer `fin m`

  /** number of rounds in key schedule */
  type T : #
  type constraint (32 <= T, T <= 72) // should infer `fin T`

  /** index of z-sequence used (i.e. use sequence z_j) */
  type j : #
  type constraint (0 <= j, j <= 4)  // should infer `fin j`

// ...
```sh
Cryptol> :m labs::SimonSpeck::Simon::Simon
Loading module labs::SimonSpeck::Simon::Simon
labs::SimonSpeck::Simon::Simon(parameterized)> :h T

    parameter T : #
    (32 <= T, T <= 72)

number of rounds in key schedule
```

Unfortunately, the documentation and type constraints don't carry over to instantiating modules, but this isn't your fault.  In any case, the docstrings should mention any further constraints from written specifications that are not convenient to express through Cryptol `type constraint`s.

"overy" -> "over"

This and `KeyWrapping` (and `TWINE`, which doesn't count) are currently the only labs in the entire course that cover import aliasing (`import {module} as {alias}`).  I've filed Issue #88 to suggest acknowledging this and import lists (`import {module} as {alias} (hiding)? ({definitions})`).

**Comment by weaversa** [comment]
> Maybe change "methods" to "functions" or change the whole bullet to something like "Know how to use basic type parameters in function definitions."

Let’s just be consistent with the prereqs sections in other labs. The bullets should mostly be verbatim with what is used elsewhere.

**Comment by weaversa** [comment]
> We should decide whether grouping all parametric type constraints together vs. defining constraints per parameter or related set of parameters is a better practice. I would lean toward the latter, as this clarifies the help documentation, 

I don’t think we should stop people from defining parameter values outside of what the spec dictates. Imagine someone that wants to do analysis on a reduced round version. It’s reasonable to support that.

**Comment by weaversa** [comment]
> This would convey more parameterized module features, but at the risk of overwhelming a new user.

I think the KISS principle definitely applies throughout this course.

**Comment by weaversa** [comment]
@WeeknightMVP that said, I do like the way you’ve laid out the module and parameters.

**Comment by WeeknightMVP** [comment]
`j` is interesting.  It looks like `j` should be a value parameter of type `[width 5]`, because there are 5 sequences from which to choose `Z` and `@` only works for bitvectors; however, type constraints straightforwardly enforce `0 <= j, j <= 4` (I think `0 <= j` is true by definition, but this might still improve readability), and it's not currently as straightforward to enforce a corresponding value "constraint".  (One way would be to declare `j: Z 5` and specify `Z = [z0, ..., z4] @ (fromInteger (fromZ j))`, which is clunky.)  I suspect this will change in Cryptol 2.9, which will generalize selectors to support indices of `Integral` type, at which point `j: Z 5` and `Z = [z0, ..., z4] @ j` would be the most straightforward.  (However, I'm not sure how this would affect proofs involving `j`.)

**Comment by jdwoolc** [comment]
This lab is really meant to be an introduction to parameterized modules -- I haven't taken a close look at the TWINE material yet... maybe we merge that here?

Also, I think the name of the lab will change in the end to labs/ParameterizedModules -- it really isn't meant to focus on Simon or Speck in any deep way, and I hadn't considered that when I started implementing Simon/Speck originally.

I'll take a look at the TWINE shortly -- maybe we can merge it in as an additional example of another PM which demonstrates additional features.

**Comment by weaversa** [comment]
TWINE could be an offshoot lab demonstrating more advanced features of parameterized modules

**Comment by jdwoolc** [comment]
Skimmed through the TWINE material -- agreed, I think Simon/Speck demonstrate a clean way in which parameterized modules are useful -- it's nice to have some additional more complex examples factored out for folks who are interested in going deeper with it.

**Comment by AssemblyZig** [comment]
(Hijacking this communication path while I fight my way back into GitHub...)

Speaking of name changes, perhaps LoremIpsum should be renamed to
Capstone?

Cheers,
Zig

**Comment by weaversa** [comment]
> `j` is interesting. It looks like `j` should be a value parameter of type `[width 5]`, because there are 5 sequences from which to choose `Z` and `@` only works for bitvectors; however, type constraints straightforwardly enforce `0 <= j, j <= 4` (I think `0 <= j` is true by definition, but this might still improve readability), and it's not currently as straightforward to enforce a corresponding value "constraint". (One way would be to declare `j: Z 5` and specify `Z = [z0, ..., z4] @ (fromInteger (fromZ j))`, which is clunky.) I suspect this will change in Cryptol 2.9, which will [generalize selectors to support indices of `Integral` type](https://github.com/GaloisInc/cryptol/pull/724), at which point `j: Z 5` and `Z = [z0, ..., z4] @ j` would be the most straightforward. (However, I'm not sure how this would affect proofs involving `j`.)

This would help: https://github.com/GaloisInc/cryptol/issues/593

**Pull request merged**
