### PR TITLE
Html

### PR DESCRIPTION
**Pull request by weaversa**
You can see the result here:

https://htmlpreview.github.io/?https://github.com/weaversa/cryptol-course/blob/html/html/README.html

Links between labs don't work yet. And, though the code blocks display ok locally in my browser, they don't display correctly via github.io.

### CODE REVIEW

**Comment by weaversa** [comment]
I used `https://github.com/phseiff/github-flavored-markdown-to-html` to render the HTML. As script go generate the HTML is in the `scripts` directory. Be careful as it uses a github api and you can only send 60 requests per hour, so it's easy to breach the limit.

**Comment by WeeknightMVP** [comment]
How does the rendering look in GitHub Pages as a project page?  Based on [GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source), if you go into `Settings` and declare `master` as the publishing source, you should see the existing [`index.html`](https://github.com/weaversa/cryptol-course/blob/master/index.html) at the URL [`https://weaversa.github.io/cryptol-course``](https://weaversa.github.io/cryptol-course).  If I understand correctly, following the link to `README.md` would render that (and other existing Markdown pages via subsequent links) same as the corresponding code view on `github.com`.  One way to find out...

This wouldn't realize many gains from generating HTML, but _neither does the rendering script_.

**Comment by weaversa** [comment]
I turned it on. Markdown is not rendered automatically.

**Comment by weaversa** [comment]
We have to do something like this:
https://nicolas-van.github.io/easy-markdown-to-github-pages/

**Comment by weaversa** [comment]
Alright. It works. Though, the markdown doesn't turn 

" ```Xcryptol session "

into a code block. Otherwise, it looks cool! I'm messing around with themes right now.

**Comment by WeeknightMVP** [comment]
Ooh, a gazpacho recipe!

Are you using the CommonMark Markdown renderer (one of the settings)?  Not sure why this behavior would be inconsistent.

But good work with the GitHub Pages setup!

**Comment by weaversa** [comment]
@WeeknightMVP Ok. It looks like `Xcryptol session` won't work, but `Xcryptol-session` will. Do you foresee any trouble changing spaces in markdown identifiers into dashes? This HTML stuff is so cool!

**Comment by weaversa** [comment]
Also, the svg course flow is not clickable as currently embedded.

**Comment by WeeknightMVP** [comment]
Also, the SVGs aren't responding to clicks on my end.  If you open it in a new tab, though, the links work.

I agree we should settle for `Xcryptol-session` for now.

**Comment by WeeknightMVP** [comment]
Also, if we use different themes, we should give the SVGs a transparent background.  Simple enough...

**Comment by WeeknightMVP** [comment]
Looks like you can [wrap SVG links with the `nomarkdown` directive](https://stackoverflow.com/questions/54013291/how-to-embed-svg-code-inside-jekyll-markdown-on-github), e.g.:

```
{::nomarkdown}
<svg ...>...</svg>
{:/}
```

No idea how the `github.com` code view would render these...

**Comment by weaversa** [comment]
@WeeknightMVP I fixed the svg issue (good enough). I see that the layercake doesn't work due to how relative pathnames are  interpreted. See: https://github.com/jekyll/jekyll/issues/332

There are workarounds...but i'm not sure what the best solution is. I would like the relative markdown links to continue to work in tools like VSCode, but also work with github.io

**Comment by weaversa** [comment]
@WeeknightMVP I tried the `{{ site.baseurl }}` solution suggested above and it linked to the correct info, but used .md extension instead of .html. So, no good.

I also tried this:
```
# From here, you can go somewhere!

Up: [Course README](../../README.md)
Previous: [Language Basics](../Language/Basics.md)
Answers: [CRC](CRCAnswers.md)
More: [Cryptol Demos](../Demos/Cryptol/Demos.md)
      [SAW Demos](../Demos/SAW/Demos.md)
Next: [Salsa20](../Salsa20/Salsa20.md)
```
Which works perfectly. You can see it in action at labs/CRC/CRC.md

Now we REALLY need that layercake autogenerator :-)

**Comment by AssemblyZig** [comment]
For what it's worth, I spent some cycles during the summer linking the
modules. Or at least trying to: I couldn't find a mechanism that worked
consistently in different domains (viewing via GitHub vs. downloaded).

Cheers,
Zig

**Pull request closed without merging**
