### PR TITLE
Salsa20 lab

### PR DESCRIPTION
**Pull request by weaversa**
To fulfill #17

### CODE REVIEW

**Comment by weaversa** [comment]
> Good start! I see that Cryptol can load the Markdown file directly

Yeah super cool! Just learned that this week.

> We might wish to retain docstrings so `:h` remains useful for interactive sessions...or we might not.

This spec is just for the lab (and really tightly integrated into the lab), which is primarily a narrative teaching how to transliterate into Cryptol. That is, I don't expect anyone to use this spec anywhere (the world has plenty of Salsa20 Cryptol specs). That said, it would be nice to demonstrate doc strings as part of the lab. We could at least mention that they are useful. Another thing I've found is that it's really kind of hard, since the lab follows the spec, to properly place low-level functions and properties in `private` blocks. So, I suggest we punt on that part as well. Perhaps when the lab finishes we leave the reader an exercise of writing the spec proper with docstrings and `private`, more test vectors, etc.

> Should we pull in the ECRYPT test vectors and additional properties?

We should definitely add a few of the simpler ones for `Salsa20_encrypt`.

**Comment by WeeknightMVP** [comment]
This being a "lab", perhaps we should leave it to the participant to fill in the blanks, similarly to Programming Foundations.  For example,

```

# The `littleendian` function

Exercise: Define `littleendian` in Cryptol by replacing `zero` with your definition below:

\`\`\`
littleendian:
    [4]Byte -> Word
littleendian b =
    zero
\`\`\`

The spec comments, "Note that `littlenedian` is invertible."

Exercise: Define `littleendian_inverse` (by replacing `zero`) and specify a `property` (by replacing `False` that it inverts `littleendian` below:

\`\`\`
littleendian_inverse:
    Word -> [4]Byte
littleendian_inverse w =
    zero

littleendian_inverse_inverts_littleendian:
    [4]Byte -> Bit
property littleendian_inverse_inverts_littleendian b =
    False

littleendian_inverts_littleendian_inverse:
    Word -> Bit
property littleendian_inverts_littleendian_inverse b =
    False
\`\`\`
```

This would give participants something to do, with a fair head start but not having the solution right in front of them.

**Comment by weaversa** [comment]
You know, that’s how we did the old lab...

How about we fill in the whole thing, and then make a copy and go back and remove things...so we have what you suggest, but also an answer key.

**Comment by WeeknightMVP** [comment]
Very good.  Why don't you go ahead and fill this in up through `Salsa20_encrypt`, and I'll start on a `Salsa20_Props.md` or something like that with test vectors and collision properties.

**Comment by WeeknightMVP** [comment]
From [The Salsa20 core](http://cr.yp.to/salsa20.html) (Bernstein):
> I originally introduced the Salsa20 core as the "Salsa20 hash function," but this terminology turns out to confuse people who think that "hash function" means "collision-resistant compression function." The Salsa20 core does not compress and is not collision-resistant.

So we should call this either `Salsa20`, or if that's too confusing, `Salsa20Core`.  We should not perpetuate this nomenclature given that the original author has reconsidered, even though the spec itself refers to the Salsa20 core as a hash function and has not been amended.

**Comment by WeeknightMVP** [comment]
On invertibility, `Salsa20.md` has a nice section tying it to bijection.  I've renamed the property to reflect that `quarterround` is **injective**, as that's what it most immediately indicates.  The exposition pretty clearly explains why it follows that `quarterround` is **invertible**.

**Comment by weaversa** [comment]
I’m up to the hash/core. So, fyi, don’t worry about polishing the last two sections yes. 

Though, @WeeknightMVP want to pick a few reasonable test vectors for the last section? Or, we could run the test generation function that comes bundled with the interpreter...might be a nice place to talk about/use that command.

**Comment by WeeknightMVP** [comment]
I'll take a crack at the test vectors.  The test vectors have apparently moved, so that'll complicate matters a bit.

**Comment by weaversa** [comment]
> From [The Salsa20 core](http://cr.yp.to/salsa20.html) (Bernstein):
> 
> > I originally introduced the Salsa20 core as the "Salsa20 hash function," but this terminology turns out to confuse people who think that "hash function" means "collision-resistant compression function." The Salsa20 core does not compress and is not collision-resistant.
> 
> So we should call this either `Salsa20`, or if that's too confusing, `Salsa20Core`. We should not perpetuate this nomenclature given that the original author has reconsidered, even though the spec itself refers to the Salsa20 core as a hash function and has not been amended.

I liked this so much I just pasted it almost verbatim into the lab. History is cool! And, I think anecdotes like this make labs more interesting. You're not just learning Cryptol, you're learning about cryptography as well.

**Comment by WeeknightMVP** [comment]
OK, I've ported the test vectors, with a note saying when they were accessed from the now-broken URL.

**Comment by weaversa** [comment]
@WeeknightMVP The only thing left for Salsa20.md are the missing test vectors for the encrypt function. Once the test vectors are in, I will split Salsa20.md into answer key and exercises.

Props.md should be updated to reflect the style of Salsa20.md. For example, you'll notice I used Camel case rather than underscores. Also, I did _a few_ of the proofs from Props.md in Salsa20.md, but the bulk of Props.md is still unique.

**Comment by WeeknightMVP** [comment]
I'll leave the integration work to you.

**Comment by weaversa** [comment]
@WeeknightMVP Are there no short messages with an interesting `v`?

**Comment by WeeknightMVP** [comment]
@weaversa These are a direct translation of all the test vectors available at that site on that date, so I suppose not.

**Comment by weaversa** [comment]
Darn...all of them also use a zero message, so how can you test whether or not you're loading in the message correctly?

**Comment by weaversa** [comment]
I'm going to modify them slightly to make them better.

**Comment by WeeknightMVP** [comment]
@weaversa How should we maintain answer sets for the exercises?  I'd have forgotten the answers for Salsa20 already if Cryptol specs weren't so ubiquitous elsewhere.

**Comment by weaversa** [comment]
How about we just put the answer set in the same directory as the lab? Ben has his bittwiddling lab set up that way. It’s essentially an online course, there’s no need not to trust the students and let them learn the material how they want. Especially since we won’t necessarily be accessible.

**Comment by WeeknightMVP** [comment]
@weaversa Sounds good to me.

**Pull request merged**
