### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by michaelabernardo**

### CODE REVIEW

**Comment by weaversa** [comment]
I kind of like the snippet tests because they run over *every* Cryptol Xsession block.

**Comment by michaelabernardo** [comment]
@weaversa I didn't realize that - added the snippet tests back in

**Comment by WeeknightMVP** [comment]
For `labs::Transposition` let's demo something a little [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)er:

```
egrep -r labs/Transposition -e "^\s*property" | grep "Answers.md" | sort
labs/Transposition/EsreverAnswers.md:property pi_test = and
labs/Transposition/RailFenceAnswers.md:property cycle_test = and
labs/Transposition/RailFenceAnswers.md:property pi_test = and
labs/Transposition/ScytaleAnswers.md:property pi_test = and
labs/Transposition/TranspositionAnswers.md:property isPermutationMapping_test = and
labs/Transposition/TranspositionAnswers.md:property isPermutation_test = and
```

```python
if __name__ == '__main__':
    c = cryptol.connect(reset_server=True)

    properties_by_module = {
        "Esrever": "pi_test",
        "RailFence": "cycle_test pi_test",
        "Scytale": "pi_test",
        "Transposition": "isPermutationMapping_test isPermutation_test",
    }

    for (mod, properties) in properties_by_module.items():
        answers = f"labs::Transposition::{mod}Answers"

        c.load_module(answers)
        print(f"Running tests in {answers}")

        for prop in properties.split():
            check(c, prop)
```

Eventually we could walk through `labs`, `c.load_file` each Markdown file passing some filter, ignore non-Cryptol Markdown, query each Cryptol Markdown for a list of properties (which would require API support or judicious `egrep` like above), and `c.check` each property.  But this is illustrative for now.

**Comment by michaelabernardo** [comment]
@weaversa I added the doc back in. Sorry about that!

Thanks, @WeeknightMVP! That is definitely way better!

**Pull request merged**
